### ISSUE TITLE
Is this project still maintained? Main script is broken.

### ISSUE THREAD

**Issue by isaachinman** [tpruvot/fullcalendar#21]
So it looks like it's been a couple years since this project started, but unfortunately it's still the only good option for a 12 month view via FullCalendar.

If I pull in the fullcalendar script from your `dist` dir and try to create a calendar with `defaultView: 'year'`, I get this error:

```
Cannot read property 'class' of undefined:
return new spec['class'](t, spec.options, viewType);
```

I went into your actual demo, and pulled the cdn version you're using there (which is apparently also 2.2.7): `http://epsy.ldtp.net/fullcalendar/dist/fullcalendar.js`. This works fine for some reason.

**Comment by tpruvot** [comment]
No there is no support, i don't use it anymore for the moment.
