### ISSUE TITLE
Readme correction

### ISSUE THREAD

**Issue by brasofilo** [tpruvot/fullcalendar#5]
Hi, Tanguy,
**_finally**_ I've managed to make it work, ufa, ain't there an easier way? ;-) 
Great stuff, well worth it :+1: 

In the readme you mention `git clone git://github.com/arshaw/fullcalendar.git` but I believe should be `/tpruvot/` instead. Well, only that worked for me :)

Doubt: when we do a `grunt`, fullcalendar.js latest version is pulled from the repository and your repo merged into it to create the output, is that correct?

**Comment by tpruvot** [comment]
yep, arshaw is the original project without the year view.

no, grunt dev compiles the exploded source files to create the final/full js (one js file)

**Comment by brasofilo** [comment]
So, I don't understand this: how to compile the most updated arshaw version with yours?
thx

**Comment by tpruvot** [comment]
This yearview is only available for the v1.6 branch. I dont plan to update
to v2 line for the moment, which require a lot of time.

2014-09-20 23:06 GMT+02:00 Rodolfo Buaiz notifications@github.com:

**Comment by brasofilo** [comment]
Oooook, got it. Thanks for the feedback!
