### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by sirtet** [tpruvot/fullcalendar#8]
Does the year-view need to be activated by argument or something?
I replaced the library, but there's no year-view...
![image](https://cloud.githubusercontent.com/assets/3509308/5184135/11a24df8-74b5-11e4-8f98-3faa121af35f.png)

**Comment by tpruvot** [comment]
yes, check the demos, you need to add "year" in the button list

2014-11-25 15:12 GMT+01:00 sirtet notifications@github.com:
